# Generated by Django 3.0.7 on 2020-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('studnet_file', models.FileField(upload_to='')),
                ('gotomeeting_file', models.FileField(upload_to='')),
            ],
        ),
    ]
