# Generated by Django 3.0.7 on 2020-09-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
    ]
