# Generated by Django 3.0.7 on 2020-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_attendance', '0002_remove_mymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('attendance', models.CharField(max_length=10)),
            ],
        ),
    ]
